print ("Jovel M. Agapay")
print ("Dawis Gasan Marinduque")
print("July 15, 2001")
print ("Marinduque State College")
print ("Bachelor of Science in Information Technology(BSIT)")
print ("2F")
print ("I like to play Basketball")
print ("I like music")
print ("I like to travel")
print ("I like watching Movies")
print ("I like playing video games")